### ISSUE TITLE
purpose of this list?

### ISSUE THREAD

**Issue by zeesh1979** [imkarthikk/pihole-facebook#3]
hi
what is the purpose of this facebook DNS list? i added to my pihole and it blocked facebook.
i came to this link while i was searching ways to block facebook ads using pihole and i thought this is what it will do but it blocked the facebook itself

**Comment by stefanw1337** [comment]
I'm not sure either, seems like a lot of text to just block facebook.com straight up. Wish it blocked ads on facebook and not the entire thing.

**Comment by Yzord** [comment]
Stop using FB!!

**Comment by arduinka55055** [comment]
this list is a bit useless
i just manually blocked facebook and all subdomains

**Comment by imkarthikk** [comment]
> this list is a bit useless
> i just manually blocked facebook and all subdomains

This list is for blocking all Facebook related domains requests via PiHole. Facebook has a ton of domains that are not known for general public. Blocking Facebook.com does not really block Facebook entirely.
